// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVzjY9fQKUbtwZD-w0485lI59EKe7nkw',
    appId: '1:902035571886:web:586b8b02af04231afcd93f',
    messagingSenderId: '902035571886',
    projectId: 'wallchain-88368',
    authDomain: 'wallchain-88368.firebaseapp.com',
    databaseURL: 'https://wallchain-88368-default-rtdb.firebaseio.com',
    storageBucket: 'wallchain-88368.appspot.com',
    measurementId: 'G-V557LHXJ9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuHvesrXEZCV19AJD1vIjPZKxIZ46-Ck',
    appId: '1:902035571886:android:e6c18d58c74a58e7fcd93f',
    messagingSenderId: '902035571886',
    projectId: 'wallchain-88368',
    databaseURL: 'https://wallchain-88368-default-rtdb.firebaseio.com',
    storageBucket: 'wallchain-88368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjgtQlWg9TjVRe5DgSbg9cvKFPLEOY1rY',
    appId: '1:902035571886:ios:ef21db5d20a7c4e7fcd93f',
    messagingSenderId: '902035571886',
    projectId: 'wallchain-88368',
    databaseURL: 'https://wallchain-88368-default-rtdb.firebaseio.com',
    storageBucket: 'wallchain-88368.appspot.com',
    iosBundleId: 'com.walchain.walchain',
  );
}
